// Auto-Generated by FAKE; do not edit
// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitle("Okanshi.WebApi")]
[assembly: AssemblyProduct("Okanshi")]
[assembly: AssemblyDescription("In-process monitoring library")]
[assembly: AssemblyVersion("6.1.0")]
[assembly: AssemblyFileVersion("6.1.0")]
[assembly: AssemblyConfiguration("Release")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Okanshi.WebApi";
        internal const System.String AssemblyProduct = "Okanshi";
        internal const System.String AssemblyDescription = "In-process monitoring library";
        internal const System.String AssemblyVersion = "6.1.0";
        internal const System.String AssemblyFileVersion = "6.1.0";
        internal const System.String AssemblyConfiguration = "Release";
    }
}
