// <auto-generated/>
using System.Reflection;

[assembly: AssemblyTitleAttribute("Okanshi.InfluxDBObserver")]
[assembly: AssemblyProductAttribute("Okanshi")]
[assembly: AssemblyDescriptionAttribute("In-process monitoring solution")]
[assembly: AssemblyFileVersionAttribute("4.0.2")]
[assembly: AssemblyVersionAttribute("4.0.0")]
[assembly: AssemblyInformationalVersionAttribute("4.0.2")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const System.String AssemblyTitle = "Okanshi.InfluxDBObserver";
        internal const System.String AssemblyProduct = "Okanshi";
        internal const System.String AssemblyDescription = "In-process monitoring solution";
        internal const System.String AssemblyFileVersion = "4.0.2";
        internal const System.String AssemblyVersion = "4.0.0";
        internal const System.String AssemblyInformationalVersion = "4.0.2";
    }
}
