// <auto-generated/>
using System.Reflection;

[assembly : AssemblyTitleAttribute("Okanshi.InfluxDBObserver")]
[assembly : AssemblyProductAttribute("Okanshi")]
[assembly : AssemblyDescriptionAttribute("In-process monitoring solution")]
[assembly : AssemblyFileVersionAttribute("5.0.0")]
[assembly : AssemblyVersionAttribute("5.0.0")]
[assembly : AssemblyInformationalVersionAttribute("5.0.0")]

namespace System
{
    internal static class AssemblyVersionInformation
    {
        internal const System.String AssemblyTitle = "Okanshi.InfluxDBObserver";
        internal const System.String AssemblyProduct = "Okanshi";
        internal const System.String AssemblyDescription = "In-process monitoring solution";
        internal const System.String AssemblyFileVersion = "5.0.0";
        internal const System.String AssemblyVersion = "5.0.0";
        internal const System.String AssemblyInformationalVersion = "5.0.0";
    }
}