// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Okanshi")>]
[<assembly: AssemblyProductAttribute("Okanshi")>]
[<assembly: AssemblyDescriptionAttribute("In-process monitoring solution")>]
[<assembly: AssemblyFileVersionAttribute("4.0.2")>]
[<assembly: AssemblyVersionAttribute("4.0.0")>]
[<assembly: AssemblyInformationalVersionAttribute("4.0.2")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Okanshi"
    let [<Literal>] AssemblyProduct = "Okanshi"
    let [<Literal>] AssemblyDescription = "In-process monitoring solution"
    let [<Literal>] AssemblyFileVersion = "4.0.2"
    let [<Literal>] AssemblyVersion = "4.0.0"
    let [<Literal>] AssemblyInformationalVersion = "4.0.2"
